package Lihad.ConflictClasses;

public enum Classes {
	ARBITER,GEOMANCER,PALADIN,DRAGOON,NINJA,THIEF,FIGHTER,TEMPEST,ARCHER,SNIPER,KNIGHT,SQUIRE,BLACK_KNIGHT,WHITE_KNIGHT,SUMMONER,BARD,MYSTIC,
	TIME_MAGE,BLUE_MAGE,RED_MAGE,BLACK_MAGE,WHITE_MAGE,CHEMIST
}
